// <auto-generated />
using System;
using EventSeatBooking.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventSeatBooking.Infrastructure.Migrations
{
    [DbContext(typeof(EventSeatBookingDbContext))]
    partial class EventSeatBookingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EventSeatBooking.Domain.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("ScreeningId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("EventSeatBooking.Domain.Entities.Screening", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ShowTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Screenings");
                });

            modelBuilder.Entity("EventSeatBooking.Domain.Entities.Booking", b =>
                {
                    b.OwnsMany("EventSeatBooking.Domain.Entities.BookedSeat", "Seats", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("BookingId")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("BookingId");

                            b1.ToTable("BookedSeat");

                            b1.WithOwner()
                                .HasForeignKey("BookingId");

                            b1.OwnsOne("EventSeatBooking.Domain.ValueObjects.SeatNumber", "SeatNumber", b2 =>
                                {
                                    b2.Property<int>("BookedSeatId")
                                        .HasColumnType("int");

                                    b2.Property<int>("Number")
                                        .HasColumnType("int")
                                        .HasColumnName("SeatColumnNumber");

                                    b2.Property<string>("Row")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)")
                                        .HasColumnName("SeatRow");

                                    b2.HasKey("BookedSeatId");

                                    b2.ToTable("BookedSeat");

                                    b2.WithOwner()
                                        .HasForeignKey("BookedSeatId");
                                });

                            b1.Navigation("SeatNumber")
                                .IsRequired();
                        });

                    b.Navigation("Seats");
                });

            modelBuilder.Entity("EventSeatBooking.Domain.Entities.Screening", b =>
                {
                    b.OwnsMany("EventSeatBooking.Domain.Entities.Seat", "Seats", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("ScreeningId")
                                .HasColumnType("int");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("Id");

                            b1.HasIndex("ScreeningId");

                            b1.ToTable("Seat");

                            b1.WithOwner()
                                .HasForeignKey("ScreeningId");

                            b1.OwnsOne("EventSeatBooking.Domain.ValueObjects.SeatNumber", "SeatNumber", b2 =>
                                {
                                    b2.Property<int>("SeatId")
                                        .HasColumnType("int");

                                    b2.Property<int>("Number")
                                        .HasColumnType("int")
                                        .HasColumnName("SeatColumnNumber");

                                    b2.Property<string>("Row")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)")
                                        .HasColumnName("SeatRow");

                                    b2.HasKey("SeatId");

                                    b2.ToTable("Seat");

                                    b2.WithOwner()
                                        .HasForeignKey("SeatId");
                                });

                            b1.Navigation("SeatNumber")
                                .IsRequired();
                        });

                    b.Navigation("Seats");
                });
#pragma warning restore 612, 618
        }
    }
}
